# Generated by Django 4.0.5 on 2022-06-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testlight', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
