# Generated by Django 4.0.5 on 2022-06-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_lights_alter_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lights',
            name='testlight',
            field=models.IntegerField(),
        ),
    ]
